# v2 syntax
version: '2'

services:
  # PHP + Nginx
  api:
    image: ambientum/php:7.2-nginx
    container_name: bycoders-api
    volumes:
      - ./api:/var/www/app
    ports:
      - "80:8080"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - frontend
      - backend

  # Vue App
  app:
    image: ambientum/node:12
    container_name: bycoders-app
    command: npm run serve
    volumes:
      - ./app:/var/www/app
    ports:
      - "8080:8080"
      - "3000:3000"
    networks:
      - frontend

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: bycoders-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    networks:
      - backend

  # Composer
  composer:
    image: ambientum/php:7.2
    container_name: bycoders-composer
    volumes:
      - ./api:/var/www/app
    command:
      - composer    
    networks:
      - backend 
 
# Named volumes
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge  